[package]
name = "remote-ext-tests-bags-list"
version = "0.9.15-1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
polkadot-runtime = { version = "0.9.15-1", path = "../../../runtime/polkadot" }
kusama-runtime = { version = "0.9.15-1", path = "../../../runtime/kusama" }
westend-runtime = { version = "0.9.15-1", path = "../../../runtime/westend" }

pallet-bags-list-remote-tests = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }

tokio = { version = "1", features = ["macros"] }
log = { version = "0.4.14" }
structopt = {version = "0.3.25" }
clap = { version = "2.33.3" }
